### ISSUE TITLE
Issues calling a contract

### ISSUE THREAD

**Issue by asbjornenge** [AndrewKishino/sotez#14]
Hi there 😄

Thanks for a great lib 🎉 I'm just getting started with Tezos and was trying out you library following https://hackernoon.com/tezos-smart-contracts-with-reasonml-docker-and-a-sandboxed-node-89df929ca1cf

I wanted to call the contract from sotez but I keep getting `TypeError: u is not a constructor`. 

I have been trying with the following:

```
const sotez = require('sotez');
const provider = "http://localhost:18731";

let keys = {
  pk: 'edp...',
  pkh: 'tz...',
  sk: 'edsk...'
} 

let payload = {
  to: 'KT1...',
  from : 'tz1...',
  keys,
  amount: 10,
  parameters: 'main 2',
}

sotez.node.setProvider(provider)

;

(async () => {
  try {
    let contract = await sotez.contract.load(payload.to) // works
    console.log(contract)
    let res = await sotez.contract.send(payload) // error
    console.log(res)
  } catch(e) {
    console.error(e)
    process.exit(1)
  }
})()
```

I'm probably using the params wrong of something. Any input? Is there some way I can use `src/sotez.node` for easier debugging? The compiled `dist` is of little help 😝

Calling the contract using `liquidity` cli works fine.

**Comment by AndrewKishino** [comment]
Liquidity uses a parameter syntax which can define entry points into different parts of a contract. I assume you are calling the main entry point for this contract which is the default. If you change your parameter to be:
```
{
  ...
  parameters: '2',
}
```
the constructed payload in the actual call gets formatted as `{ int: '2' }`.

What I found really useful was using [liquidity's online IDE](http://www.liquidity-lang.org/) with the developer tools network tab open and try forging operations and see how your parameters are being formatted in the forging calls.

**Comment by asbjornenge** [comment]
Tried that too, but getting the same error 🤔 It seems to be related to the `mutez` parameter...? When I set that to `true` I get a different error. Here is the stack:

```
TypeError: u is not a constructor
    at Object.mutez (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:90246)
    at Object.transfer (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:103067)
    at Object.send (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:108366)
    at /srv/asbjornenge/tezos-environment-manager/examples/updateContract.js:26:36
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by AndrewKishino** [comment]
I was able to recreate the issue. Seems like it was caused by this issue https://github.com/MikeMcl/bignumber.js/issues/217 from bignumber. Anyways, I pushed a fix and updated the version. Update your version to `0.2.6` and see if it is working for you.

**Comment by AndrewKishino** [comment]
@asbjornenge Looks like I may have introduced a small bug when forging ints. New version should be up. Go ahead and give it a try. Thanks for being so patient!

**Comment by asbjornenge** [comment]
@AndrewKishino nono, thank YOU for creating this module and helping out 😬👍

Got further this time, but got stuck on signing;

```
TypeError: invalid privateKey length
    at E (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:7:50002)
    at Object.VA [as crypto_sign_detached] (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:7:86566)
    at Object.sign (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:94160)
    at /srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:110484
    at y (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:85219)
    at Generator._invoke (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:85007)
    at Generator.A.(anonymous function) [as next] (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:85398)
    at i (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:87952)
    at a (/srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:88154)
    at /srv/asbjornenge/tezos-environment-manager/examples/node_modules/sotez/dist/sotez.node.js:1:88213
```

I forked the module and messed about a bit 😝 Had some issues with babel and the tests, so I made a commit that fixes it for me. You can take a peak here https://github.com/asbjornenge/sotez/commit/f5c02702339aa41c9edc19a103824dd925f29e2f - I'll be happy to PR this if you want it.

But, once the tests were up and running I managed to reproduce the error by uncommenting the `sign` test and passing a tezos `sk` to the `crypto.sign` function. Hope that helps with debugging 👍

**Comment by AndrewKishino** [comment]
So this error is valid, however the current implementation only supports secret keys which are generated through sotez, or ledger hardware wallets. If you generate a new address using sotez and use that as your keys, that should resolve this latest issue you are seeing.

**Comment by AndrewKishino** [comment]
@asbjornenge I pushed a change that should detect which sk format you are using and extracts the sk format you can use to sign messages. Hopefully this helps! 🙏

**Comment by asbjornenge** [comment]
Fantastic 🎉 I can now sign 🚀 Thanks a bunch for all your help!

I still get an error:

```
[{"kind":"generic","error":"Operation ooyZrcyeBjYFkC8Yr9t5VwDSn4HvUVWu5gsLQHW3QdEHppYonbo rejected by the mempool pre filter"}]
```

Any idea what this means? Probably something to do with my node or the params I'm sending...? 🤔

**Comment by AndrewKishino** [comment]
You may need to set a higher `fee`.

**Comment by asbjornenge** [comment]
Tried setting the `fee: 1` which is what I did with liquidity-cli but still same issue 🤔 Getting an error if I try to set it to `0.5`.

```
Failed to parse the request body: No case matched:
  At /kind, unexpected string instead of endorsement
  At /kind, unexpected string instead of seed_nonce_revelation
  At /kind, unexpected string instead of double_endorsement_evidence
  At /kind, unexpected string instead of double_baking_evidence
  At /kind, unexpected string instead of activate_account
  At /kind, unexpected string instead of proposals
  At /kind, unexpected string instead of ballot
  At /kind, unexpected string instead of reveal
  Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
  At /kind, unexpected string instead of origination
  At /kind, unexpected string instead of delegation
```

**Comment by AndrewKishino** [comment]
The fee is expressed as mutez (1/1,000,000 of a tez) the default fee for transfers is set to `1278` so for a contract you may need to set it  a bit higher due to the computations of the contract. If you're in a test environment, I would just start playing with the fee values and possibly the gasLimit and storageLimit values to find what works best for your use case.

**Comment by asbjornenge** [comment]
@AndrewKishino aha! That worked 😬🎉 I was fiddling with those other params too, but kept the fee too low.

The docs says `0.05` is the default 🤷‍♂️🙈

Again, thanks for all your help with this issue! I'm going to continue exploring Tezos and this lib 😉👍

**Comment by AndrewKishino** [comment]
Will update the docs to reflect the correct fees. Thanks!
